// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tick_IT.Data;

namespace Tick_IT.Migrations
{
    [DbContext(typeof(TickITContext))]
    [Migration("20200207125112_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.Issues_Number", "'Issues_Number', '', '10001', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tick_IT.Models.Issues", b =>
                {
                    b.Property<Guid>("Issues_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Issues_Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Issues_DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Issues_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Issues_Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR Issues_Number");

                    b.Property<int?>("Issues_Status")
                        .HasColumnType("int");

                    b.Property<string>("Issues_Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Issues_UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Issues_ID");

                    b.ToTable("Issue");
                });

            modelBuilder.Entity("Tick_IT.Models.Responses", b =>
                {
                    b.Property<Guid>("Responses_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Issues_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Responses_CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Responses_DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Responses_Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Responses_TicketID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Responses_UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Responses_ID");

                    b.HasIndex("Issues_ID");

                    b.ToTable("Response");
                });

            modelBuilder.Entity("Tick_IT.Models.Responses", b =>
                {
                    b.HasOne("Tick_IT.Models.Issues", "Issues")
                        .WithMany("Responses")
                        .HasForeignKey("Issues_ID");
                });
#pragma warning restore 612, 618
        }
    }
}
